### ISSUE TITLE
memmove() does not handle overlapping areas correctly

### ISSUE THREAD

**Issue by k-th** [TatsuMaster/Tatsu-Development-Kit#2]
For the case where source and destination memory areas overlap and 'source address' < 'destination address' (s2 < s1), the memmove() result is not correct: the copy operation should begin at the end of the memory areas and go backwards.

Feel free to adapt the code from this patch (w.r.t. coding style etc.):

[tatsu-memmove.patch.txt](https://github.com/TatsuMaster/Tatsu-Development-Kit/files/1337463/tatsu-memmove.patch.txt)

On another note, it would also be possible to omit the 'end_address' variable by re-using parameter 'n':

`while ((n--) > 0)`

**Comment by TatsuMaster** [comment]
Thank you! This is a nice one. I will review your patch and develop an suitable fix for this one you may want to review too. The test suite should be strengthen as well to cover this issue.

**Comment by TatsuMaster** [comment]
Adapted your patch. memmove should work as expected now.
